"""
Author: Wei
Generate notes.inc file for player.inc
"""

F_CPU = 1e6
N = 8


def F_PIANO(N): return 440 * (2 ** ((N - 49) / 12))
def OCRN(F): return F_CPU / (2 * F * N) - 1


PREFIX = "NOTE_"
SYMBOLS = """
DO  DOS    RE  RES    MI  FA  FAS    SO  SOS    LA  LAS    SI
DOH DOHS   REH REHS   MIH FAH FAHS   SOH SOHS   LAH LAHS   SIH
""".split()

LEN = len(SYMBOLS)
OFFSET = 40


TEMPLATE = """
; Generated by notes_gen.py

; Note IDs
%(equates)s

; Beat Ids
.equ NOTE_Q = 1 << 5
.equ NOTE_H = 2 << 5
.equ NOTE_W = 4 << 5

.cseg

NOTES: .db %(values)s

"""


if __name__ == "__main__":

    values = []
    equates = []

    for i in range(LEN):
        v = round(OCRN(F_PIANO(i + OFFSET)))
        values.append(str(v))
        equates.append(f".equ {PREFIX}{SYMBOLS[i]} = {i}")

    equates.append(f".equ NOTE_SILENCE = {LEN}")

    with open("notes.inc", "w") as f:
        f.write(TEMPLATE % {
            "equates": "\n".join(equates),
            "values": ", ".join(values)
        })
