name: ci

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Build Web
        run: |
          cd web
          npm ci
          mv next.docker.config.mjs next.config.mjs
          npm run build
          mv _config.yml build
          mv build ../docs
      - name: Push
        env:
          MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          git add .
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "$MESSAGE"
          git push origin main:build -f